### ISSUE TITLE
Wrong arxiv paper link in README.md

### ISSUE THREAD

**Issue by dslisleedh** [Jiamian-Wang/SR_pruning_official#1]
Hi, @Jiamian-Wang

Firstly, thank you for the great work. But there's something wrong with the hyperlink in README.
The current paper hyperlink is connected to CAT(https://arxiv.org/abs/2211.13654), not Iterative-Soft-Shrinkage-SR(https://arxiv.org/abs/2303.09650). 

I hope this helps.
Thank you.

**Comment by Jiamian-Wang** [comment]
Dear @dslisleedh, 

Thank you so much for pointing out the typo! 
I have fixed it in [README](https://github.com/Jiamian-Wang/Iterative-Soft-Shrinkage-SR/blob/main/README.md). 

Please let me know if there is anything that I can help~

Thanks,
Jiamian
